#permalink: pretty

title: My Family Story
email: myfamilystorybest@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Build your family story on your own computer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://myfamilystory.best" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  my-family-story

logo:
  mobile: "images/logo/icons8-family-64.png"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/icons8-family-64.png"
  desktop_height: "64px"
  desktop_width: "64px"

collections:
  services:
    output: false
  team:
    output: false

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"
# https://myfamilystory.canny.io/my-family-story-feature-request
# https://myfamilystory.youtrack.cloud/issues

sass:
  indentWidth: 4
  style: compressed # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
